CREATE TABLE microdados
(
	NU_INSCRICAO varchar(12),
	NU_ANO integer,
	CO_MUNICIPIO_RESIDENCIA integer,
	TP_PRESENCA_CN boolean,
	TP_PRESENCA_CH boolean,
	TP_PRESENCA_LC boolean,
	TP_PRESENCA_MT boolean,
	CO_PROVA_CN integer,
	CO_PROVA_CH integer,
	CO_PROVA_LC integer,
	CO_PROVA_MT integer,
	NU_NOTA_CN numeric,
	NU_NOTA_CH numeric,
	NU_NOTA_LC numeric,
	NU_NOTA_MT numeric,
	TX_RESPOSTAS_CN varchar(45),
	TX_RESPOSTAS_CH varchar(45),
	TX_RESPOSTAS_LC varchar(50),
	TX_RESPOSTAS_MT varchar(45),
	TP_LINGUA integer,
	TX_GABARITO_CN varchar(45),
	TX_GABARITO_CH varchar(45),
	TX_GABARITO_LC varchar(50),
	TX_GABARITO_MT varchar(45),
	TP_STATUS_REDACAO integer,
	NU_NOTA_COMP1 numeric,
	NU_NOTA_COMP2 numeric,
	NU_NOTA_COMP3 numeric,
	NU_NOTA_COMP4 numeric,
	NU_NOTA_COMP5 numeric,
	NU_NOTA_REDACAO numeric,
	CONSTRAINT microdados_pkey PRIMARY KEY (NU_INSCRICAO, NU_ANO)
);

